// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/protobuf/Student.proto

package com.yejunyu.protobuf;

public final class DataInfo {
    private DataInfo() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface StudentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.yejunyu.protobuf.Student)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string name = 1;</code>
         *
         * @return Whether the name field is set.
         */
        boolean hasName();

        /**
         * <code>required string name = 1;</code>
         *
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>required string name = 1;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>optional int32 age = 2;</code>
         *
         * @return Whether the age field is set.
         */
        boolean hasAge();

        /**
         * <code>optional int32 age = 2;</code>
         *
         * @return The age.
         */
        int getAge();

        /**
         * <code>optional string address = 3;</code>
         *
         * @return Whether the address field is set.
         */
        boolean hasAddress();

        /**
         * <code>optional string address = 3;</code>
         *
         * @return The address.
         */
        java.lang.String getAddress();

        /**
         * <code>optional string address = 3;</code>
         *
         * @return The bytes for address.
         */
        com.google.protobuf.ByteString
        getAddressBytes();

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        java.util.List<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber>
        getPhoneList();

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        com.yejunyu.protobuf.DataInfo.Student.PhoneNumber getPhone(int index);

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        int getPhoneCount();

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        java.util.List<? extends com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder>
        getPhoneOrBuilderList();

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code com.yejunyu.protobuf.Student}
     */
    public static final class Student extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.yejunyu.protobuf.Student)
            StudentOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Student.newBuilder() to construct.
        private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Student() {
            name_ = "";
            address_ = "";
            phone_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Student();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Student(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            name_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            age_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            address_ = bs;
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                                phone_ = new java.util.ArrayList<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber>();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            phone_.add(
                                    input.readMessage(com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.PARSER, extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000008) != 0)) {
                    phone_ = java.util.Collections.unmodifiableList(phone_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.yejunyu.protobuf.DataInfo.Student.class, com.yejunyu.protobuf.DataInfo.Student.Builder.class);
        }

        /**
         * Protobuf enum {@code com.yejunyu.protobuf.Student.PhoneType}
         */
        public enum PhoneType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>MOBILE = 0;</code>
             */
            MOBILE(0),
            /**
             * <code>HOME = 1;</code>
             */
            HOME(1),
            /**
             * <code>WORK = 2;</code>
             */
            WORK(2),
            ;

            /**
             * <code>MOBILE = 0;</code>
             */
            public static final int MOBILE_VALUE = 0;
            /**
             * <code>HOME = 1;</code>
             */
            public static final int HOME_VALUE = 1;
            /**
             * <code>WORK = 2;</code>
             */
            public static final int WORK_VALUE = 2;


            public final int getNumber() {
                return value;
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static PhoneType valueOf(int value) {
                return forNumber(value);
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             */
            public static PhoneType forNumber(int value) {
                switch (value) {
                    case 0:
                        return MOBILE;
                    case 1:
                        return HOME;
                    case 2:
                        return WORK;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
            internalGetValueMap() {
                return internalValueMap;
            }

            private static final com.google.protobuf.Internal.EnumLiteMap<
                    PhoneType> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                        public PhoneType findValueByNumber(int number) {
                            return PhoneType.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return com.yejunyu.protobuf.DataInfo.Student.getDescriptor().getEnumTypes().get(0);
            }

            private static final PhoneType[] VALUES = values();

            public static PhoneType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private PhoneType(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:com.yejunyu.protobuf.Student.PhoneType)
        }

        public interface PhoneNumberOrBuilder extends
                // @@protoc_insertion_point(interface_extends:com.yejunyu.protobuf.Student.PhoneNumber)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>optional string number = 1;</code>
             *
             * @return Whether the number field is set.
             */
            boolean hasNumber();

            /**
             * <code>optional string number = 1;</code>
             *
             * @return The number.
             */
            java.lang.String getNumber();

            /**
             * <code>optional string number = 1;</code>
             *
             * @return The bytes for number.
             */
            com.google.protobuf.ByteString
            getNumberBytes();

            /**
             * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
             *
             * @return Whether the type field is set.
             */
            boolean hasType();

            /**
             * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
             *
             * @return The type.
             */
            com.yejunyu.protobuf.DataInfo.Student.PhoneType getType();
        }

        /**
         * Protobuf type {@code com.yejunyu.protobuf.Student.PhoneNumber}
         */
        public static final class PhoneNumber extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:com.yejunyu.protobuf.Student.PhoneNumber)
                PhoneNumberOrBuilder {
            private static final long serialVersionUID = 0L;

            // Use PhoneNumber.newBuilder() to construct.
            private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }

            private PhoneNumber() {
                number_ = "";
                type_ = 1;
            }

            @java.lang.Override
            @SuppressWarnings({"unused"})
            protected java.lang.Object newInstance(
                    UnusedPrivateParameter unused) {
                return new PhoneNumber();
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }

            private PhoneNumber(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000001;
                                number_ = bs;
                                break;
                            }
                            case 16: {
                                int rawValue = input.readEnum();
                                @SuppressWarnings("deprecation")
                                com.yejunyu.protobuf.DataInfo.Student.PhoneType value = com.yejunyu.protobuf.DataInfo.Student.PhoneType.valueOf(rawValue);
                                if (value == null) {
                                    unknownFields.mergeVarintField(2, rawValue);
                                } else {
                                    bitField0_ |= 0x00000002;
                                    type_ = rawValue;
                                }
                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_PhoneNumber_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_PhoneNumber_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.class, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder.class);
            }

            private int bitField0_;
            public static final int NUMBER_FIELD_NUMBER = 1;
            private volatile java.lang.Object number_;

            /**
             * <code>optional string number = 1;</code>
             *
             * @return Whether the number field is set.
             */
            @java.lang.Override
            public boolean hasNumber() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional string number = 1;</code>
             *
             * @return The number.
             */
            @java.lang.Override
            public java.lang.String getNumber() {
                java.lang.Object ref = number_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        number_ = s;
                    }
                    return s;
                }
            }

            /**
             * <code>optional string number = 1;</code>
             *
             * @return The bytes for number.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getNumberBytes() {
                java.lang.Object ref = number_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    number_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int TYPE_FIELD_NUMBER = 2;
            private int type_;

            /**
             * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
             *
             * @return Whether the type field is set.
             */
            @java.lang.Override
            public boolean hasType() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
             *
             * @return The type.
             */
            @java.lang.Override
            public com.yejunyu.protobuf.DataInfo.Student.PhoneType getType() {
                @SuppressWarnings("deprecation")
                com.yejunyu.protobuf.DataInfo.Student.PhoneType result = com.yejunyu.protobuf.DataInfo.Student.PhoneType.valueOf(type_);
                return result == null ? com.yejunyu.protobuf.DataInfo.Student.PhoneType.HOME : result;
            }

            private byte memoizedIsInitialized = -1;

            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (((bitField0_ & 0x00000001) != 0)) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
                }
                if (((bitField0_ & 0x00000002) != 0)) {
                    output.writeEnum(2, type_);
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (((bitField0_ & 0x00000001) != 0)) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
                }
                if (((bitField0_ & 0x00000002) != 0)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeEnumSize(2, type_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof com.yejunyu.protobuf.DataInfo.Student.PhoneNumber)) {
                    return super.equals(obj);
                }
                com.yejunyu.protobuf.DataInfo.Student.PhoneNumber other = (com.yejunyu.protobuf.DataInfo.Student.PhoneNumber) obj;

                if (hasNumber() != other.hasNumber()) return false;
                if (hasNumber()) {
                    if (!getNumber()
                            .equals(other.getNumber())) return false;
                }
                if (hasType() != other.hasType()) return false;
                if (hasType()) {
                    if (type_ != other.type_) return false;
                }
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                if (hasNumber()) {
                    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
                    hash = (53 * hash) + getNumber().hashCode();
                }
                if (hasType()) {
                    hash = (37 * hash) + TYPE_FIELD_NUMBER;
                    hash = (53 * hash) + type_;
                }
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @java.lang.Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(com.yejunyu.protobuf.DataInfo.Student.PhoneNumber prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code com.yejunyu.protobuf.Student.PhoneNumber}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:com.yejunyu.protobuf.Student.PhoneNumber)
                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_PhoneNumber_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_PhoneNumber_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.class, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder.class);
                }

                // Construct using com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }

                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    number_ = "";
                    bitField0_ = (bitField0_ & ~0x00000001);
                    type_ = 1;
                    bitField0_ = (bitField0_ & ~0x00000002);
                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_PhoneNumber_descriptor;
                }

                @java.lang.Override
                public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber getDefaultInstanceForType() {
                    return com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.getDefaultInstance();
                }

                @java.lang.Override
                public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber build() {
                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumber result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber buildPartial() {
                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumber result = new com.yejunyu.protobuf.DataInfo.Student.PhoneNumber(this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) != 0)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.number_ = number_;
                    if (((from_bitField0_ & 0x00000002) != 0)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.type_ = type_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }

                @java.lang.Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.setField(field, value);
                }

                @java.lang.Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }

                @java.lang.Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }

                @java.lang.Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }

                @java.lang.Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }

                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof com.yejunyu.protobuf.DataInfo.Student.PhoneNumber) {
                        return mergeFrom((com.yejunyu.protobuf.DataInfo.Student.PhoneNumber) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(com.yejunyu.protobuf.DataInfo.Student.PhoneNumber other) {
                    if (other == com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.getDefaultInstance()) return this;
                    if (other.hasNumber()) {
                        bitField0_ |= 0x00000001;
                        number_ = other.number_;
                        onChanged();
                    }
                    if (other.hasType()) {
                        setType(other.getType());
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumber parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (com.yejunyu.protobuf.DataInfo.Student.PhoneNumber) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private int bitField0_;

                private java.lang.Object number_ = "";

                /**
                 * <code>optional string number = 1;</code>
                 *
                 * @return Whether the number field is set.
                 */
                public boolean hasNumber() {
                    return ((bitField0_ & 0x00000001) != 0);
                }

                /**
                 * <code>optional string number = 1;</code>
                 *
                 * @return The number.
                 */
                public java.lang.String getNumber() {
                    java.lang.Object ref = number_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            number_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>optional string number = 1;</code>
                 *
                 * @return The bytes for number.
                 */
                public com.google.protobuf.ByteString
                getNumberBytes() {
                    java.lang.Object ref = number_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        number_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>optional string number = 1;</code>
                 *
                 * @param value The number to set.
                 * @return This builder for chaining.
                 */
                public Builder setNumber(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    number_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string number = 1;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearNumber() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    number_ = getDefaultInstance().getNumber();
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string number = 1;</code>
                 *
                 * @param value The bytes for number to set.
                 * @return This builder for chaining.
                 */
                public Builder setNumberBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    number_ = value;
                    onChanged();
                    return this;
                }

                private int type_ = 1;

                /**
                 * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
                 *
                 * @return Whether the type field is set.
                 */
                @java.lang.Override
                public boolean hasType() {
                    return ((bitField0_ & 0x00000002) != 0);
                }

                /**
                 * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
                 *
                 * @return The type.
                 */
                @java.lang.Override
                public com.yejunyu.protobuf.DataInfo.Student.PhoneType getType() {
                    @SuppressWarnings("deprecation")
                    com.yejunyu.protobuf.DataInfo.Student.PhoneType result = com.yejunyu.protobuf.DataInfo.Student.PhoneType.valueOf(type_);
                    return result == null ? com.yejunyu.protobuf.DataInfo.Student.PhoneType.HOME : result;
                }

                /**
                 * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
                 *
                 * @param value The type to set.
                 * @return This builder for chaining.
                 */
                public Builder setType(com.yejunyu.protobuf.DataInfo.Student.PhoneType value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    type_ = value.getNumber();
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional .com.yejunyu.protobuf.Student.PhoneType type = 2 [default = HOME];</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearType() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    type_ = 1;
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:com.yejunyu.protobuf.Student.PhoneNumber)
            }

            // @@protoc_insertion_point(class_scope:com.yejunyu.protobuf.Student.PhoneNumber)
            private static final com.yejunyu.protobuf.DataInfo.Student.PhoneNumber DEFAULT_INSTANCE;

            static {
                DEFAULT_INSTANCE = new com.yejunyu.protobuf.DataInfo.Student.PhoneNumber();
            }

            public static com.yejunyu.protobuf.DataInfo.Student.PhoneNumber getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            @java.lang.Deprecated
            public static final com.google.protobuf.Parser<PhoneNumber>
                    PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
                @java.lang.Override
                public PhoneNumber parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new PhoneNumber(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<PhoneNumber> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        private int bitField0_;
        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;

        /**
         * <code>required string name = 1;</code>
         *
         * @return Whether the name field is set.
         */
        @java.lang.Override
        public boolean hasName() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required string name = 1;</code>
         *
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string name = 1;</code>
         *
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AGE_FIELD_NUMBER = 2;
        private int age_;

        /**
         * <code>optional int32 age = 2;</code>
         *
         * @return Whether the age field is set.
         */
        @java.lang.Override
        public boolean hasAge() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional int32 age = 2;</code>
         *
         * @return The age.
         */
        @java.lang.Override
        public int getAge() {
            return age_;
        }

        public static final int ADDRESS_FIELD_NUMBER = 3;
        private volatile java.lang.Object address_;

        /**
         * <code>optional string address = 3;</code>
         *
         * @return Whether the address field is set.
         */
        @java.lang.Override
        public boolean hasAddress() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional string address = 3;</code>
         *
         * @return The address.
         */
        @java.lang.Override
        public java.lang.String getAddress() {
            java.lang.Object ref = address_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    address_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string address = 3;</code>
         *
         * @return The bytes for address.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getAddressBytes() {
            java.lang.Object ref = address_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                address_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PHONE_FIELD_NUMBER = 4;
        private java.util.List<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber> phone_;

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        @java.lang.Override
        public java.util.List<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber> getPhoneList() {
            return phone_;
        }

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        @java.lang.Override
        public java.util.List<? extends com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder>
        getPhoneOrBuilderList() {
            return phone_;
        }

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        @java.lang.Override
        public int getPhoneCount() {
            return phone_.size();
        }

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        @java.lang.Override
        public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber getPhone(int index) {
            return phone_.get(index);
        }

        /**
         * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
         */
        @java.lang.Override
        public com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
                int index) {
            return phone_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeInt32(2, age_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
            }
            for (int i = 0; i < phone_.size(); i++) {
                output.writeMessage(4, phone_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, age_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
            }
            for (int i = 0; i < phone_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, phone_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.yejunyu.protobuf.DataInfo.Student)) {
                return super.equals(obj);
            }
            com.yejunyu.protobuf.DataInfo.Student other = (com.yejunyu.protobuf.DataInfo.Student) obj;

            if (hasName() != other.hasName()) return false;
            if (hasName()) {
                if (!getName()
                        .equals(other.getName())) return false;
            }
            if (hasAge() != other.hasAge()) return false;
            if (hasAge()) {
                if (getAge()
                        != other.getAge()) return false;
            }
            if (hasAddress() != other.hasAddress()) return false;
            if (hasAddress()) {
                if (!getAddress()
                        .equals(other.getAddress())) return false;
            }
            if (!getPhoneList()
                    .equals(other.getPhoneList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasName()) {
                hash = (37 * hash) + NAME_FIELD_NUMBER;
                hash = (53 * hash) + getName().hashCode();
            }
            if (hasAge()) {
                hash = (37 * hash) + AGE_FIELD_NUMBER;
                hash = (53 * hash) + getAge();
            }
            if (hasAddress()) {
                hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
                hash = (53 * hash) + getAddress().hashCode();
            }
            if (getPhoneCount() > 0) {
                hash = (37 * hash) + PHONE_FIELD_NUMBER;
                hash = (53 * hash) + getPhoneList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.yejunyu.protobuf.DataInfo.Student parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.yejunyu.protobuf.DataInfo.Student prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.yejunyu.protobuf.Student}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.yejunyu.protobuf.Student)
                com.yejunyu.protobuf.DataInfo.StudentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.yejunyu.protobuf.DataInfo.Student.class, com.yejunyu.protobuf.DataInfo.Student.Builder.class);
            }

            // Construct using com.yejunyu.protobuf.DataInfo.Student.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getPhoneFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                age_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                address_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                if (phoneBuilder_ == null) {
                    phone_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                } else {
                    phoneBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.yejunyu.protobuf.DataInfo.internal_static_com_yejunyu_protobuf_Student_descriptor;
            }

            @java.lang.Override
            public com.yejunyu.protobuf.DataInfo.Student getDefaultInstanceForType() {
                return com.yejunyu.protobuf.DataInfo.Student.getDefaultInstance();
            }

            @java.lang.Override
            public com.yejunyu.protobuf.DataInfo.Student build() {
                com.yejunyu.protobuf.DataInfo.Student result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.yejunyu.protobuf.DataInfo.Student buildPartial() {
                com.yejunyu.protobuf.DataInfo.Student result = new com.yejunyu.protobuf.DataInfo.Student(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.age_ = age_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.address_ = address_;
                if (phoneBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) != 0)) {
                        phone_ = java.util.Collections.unmodifiableList(phone_);
                        bitField0_ = (bitField0_ & ~0x00000008);
                    }
                    result.phone_ = phone_;
                } else {
                    result.phone_ = phoneBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.yejunyu.protobuf.DataInfo.Student) {
                    return mergeFrom((com.yejunyu.protobuf.DataInfo.Student) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.yejunyu.protobuf.DataInfo.Student other) {
                if (other == com.yejunyu.protobuf.DataInfo.Student.getDefaultInstance()) return this;
                if (other.hasName()) {
                    bitField0_ |= 0x00000001;
                    name_ = other.name_;
                    onChanged();
                }
                if (other.hasAge()) {
                    setAge(other.getAge());
                }
                if (other.hasAddress()) {
                    bitField0_ |= 0x00000004;
                    address_ = other.address_;
                    onChanged();
                }
                if (phoneBuilder_ == null) {
                    if (!other.phone_.isEmpty()) {
                        if (phone_.isEmpty()) {
                            phone_ = other.phone_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                        } else {
                            ensurePhoneIsMutable();
                            phone_.addAll(other.phone_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.phone_.isEmpty()) {
                        if (phoneBuilder_.isEmpty()) {
                            phoneBuilder_.dispose();
                            phoneBuilder_ = null;
                            phone_ = other.phone_;
                            bitField0_ = (bitField0_ & ~0x00000008);
                            phoneBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getPhoneFieldBuilder() : null;
                        } else {
                            phoneBuilder_.addAllMessages(other.phone_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasName()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.yejunyu.protobuf.DataInfo.Student parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.yejunyu.protobuf.DataInfo.Student) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object name_ = "";

            /**
             * <code>required string name = 1;</code>
             *
             * @return Whether the name field is set.
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required string name = 1;</code>
             *
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string name = 1;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string name = 1;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 1;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }

            private int age_;

            /**
             * <code>optional int32 age = 2;</code>
             *
             * @return Whether the age field is set.
             */
            @java.lang.Override
            public boolean hasAge() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional int32 age = 2;</code>
             *
             * @return The age.
             */
            @java.lang.Override
            public int getAge() {
                return age_;
            }

            /**
             * <code>optional int32 age = 2;</code>
             *
             * @param value The age to set.
             * @return This builder for chaining.
             */
            public Builder setAge(int value) {
                bitField0_ |= 0x00000002;
                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 age = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAge() {
                bitField0_ = (bitField0_ & ~0x00000002);
                age_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object address_ = "";

            /**
             * <code>optional string address = 3;</code>
             *
             * @return Whether the address field is set.
             */
            public boolean hasAddress() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional string address = 3;</code>
             *
             * @return The address.
             */
            public java.lang.String getAddress() {
                java.lang.Object ref = address_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        address_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string address = 3;</code>
             *
             * @return The bytes for address.
             */
            public com.google.protobuf.ByteString
            getAddressBytes() {
                java.lang.Object ref = address_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    address_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string address = 3;</code>
             *
             * @param value The address to set.
             * @return This builder for chaining.
             */
            public Builder setAddress(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                address_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string address = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAddress() {
                bitField0_ = (bitField0_ & ~0x00000004);
                address_ = getDefaultInstance().getAddress();
                onChanged();
                return this;
            }

            /**
             * <code>optional string address = 3;</code>
             *
             * @param value The bytes for address to set.
             * @return This builder for chaining.
             */
            public Builder setAddressBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                address_ = value;
                onChanged();
                return this;
            }

            private java.util.List<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber> phone_ =
                    java.util.Collections.emptyList();

            private void ensurePhoneIsMutable() {
                if (!((bitField0_ & 0x00000008) != 0)) {
                    phone_ = new java.util.ArrayList<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber>(phone_);
                    bitField0_ |= 0x00000008;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumber, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder, com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder> phoneBuilder_;

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public java.util.List<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber> getPhoneList() {
                if (phoneBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(phone_);
                } else {
                    return phoneBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public int getPhoneCount() {
                if (phoneBuilder_ == null) {
                    return phone_.size();
                } else {
                    return phoneBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber getPhone(int index) {
                if (phoneBuilder_ == null) {
                    return phone_.get(index);
                } else {
                    return phoneBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder setPhone(
                    int index, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber value) {
                if (phoneBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhoneIsMutable();
                    phone_.set(index, value);
                    onChanged();
                } else {
                    phoneBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder setPhone(
                    int index, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder builderForValue) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    phoneBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder addPhone(com.yejunyu.protobuf.DataInfo.Student.PhoneNumber value) {
                if (phoneBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhoneIsMutable();
                    phone_.add(value);
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder addPhone(
                    int index, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber value) {
                if (phoneBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePhoneIsMutable();
                    phone_.add(index, value);
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder addPhone(
                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder builderForValue) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.add(builderForValue.build());
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder addPhone(
                    int index, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder builderForValue) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    phoneBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder addAllPhone(
                    java.lang.Iterable<? extends com.yejunyu.protobuf.DataInfo.Student.PhoneNumber> values) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, phone_);
                    onChanged();
                } else {
                    phoneBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder clearPhone() {
                if (phoneBuilder_ == null) {
                    phone_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000008);
                    onChanged();
                } else {
                    phoneBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public Builder removePhone(int index) {
                if (phoneBuilder_ == null) {
                    ensurePhoneIsMutable();
                    phone_.remove(index);
                    onChanged();
                } else {
                    phoneBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder getPhoneBuilder(
                    int index) {
                return getPhoneFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
                    int index) {
                if (phoneBuilder_ == null) {
                    return phone_.get(index);
                } else {
                    return phoneBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public java.util.List<? extends com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder>
            getPhoneOrBuilderList() {
                if (phoneBuilder_ != null) {
                    return phoneBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(phone_);
                }
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder addPhoneBuilder() {
                return getPhoneFieldBuilder().addBuilder(
                        com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.getDefaultInstance());
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder addPhoneBuilder(
                    int index) {
                return getPhoneFieldBuilder().addBuilder(
                        index, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.getDefaultInstance());
            }

            /**
             * <code>repeated .com.yejunyu.protobuf.Student.PhoneNumber phone = 4;</code>
             */
            public java.util.List<com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder>
            getPhoneBuilderList() {
                return getPhoneFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.yejunyu.protobuf.DataInfo.Student.PhoneNumber, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder, com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder>
            getPhoneFieldBuilder() {
                if (phoneBuilder_ == null) {
                    phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            com.yejunyu.protobuf.DataInfo.Student.PhoneNumber, com.yejunyu.protobuf.DataInfo.Student.PhoneNumber.Builder, com.yejunyu.protobuf.DataInfo.Student.PhoneNumberOrBuilder>(
                            phone_,
                            ((bitField0_ & 0x00000008) != 0),
                            getParentForChildren(),
                            isClean());
                    phone_ = null;
                }
                return phoneBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.yejunyu.protobuf.Student)
        }

        // @@protoc_insertion_point(class_scope:com.yejunyu.protobuf.Student)
        private static final com.yejunyu.protobuf.DataInfo.Student DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.yejunyu.protobuf.DataInfo.Student();
        }

        public static com.yejunyu.protobuf.DataInfo.Student getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Student>
                PARSER = new com.google.protobuf.AbstractParser<Student>() {
            @java.lang.Override
            public Student parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Student(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Student> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Student> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.yejunyu.protobuf.DataInfo.Student getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_yejunyu_protobuf_Student_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_yejunyu_protobuf_Student_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_yejunyu_protobuf_Student_PhoneNumber_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_yejunyu_protobuf_Student_PhoneNumber_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n$src/main/java/protobuf/Student.proto\022\024" +
                        "com.yejunyu.protobuf\"\370\001\n\007Student\022\014\n\004name" +
                        "\030\001 \002(\t\022\013\n\003age\030\002 \001(\005\022\017\n\007address\030\003 \001(\t\0228\n\005" +
                        "phone\030\004 \003(\0132).com.yejunyu.protobuf.Stude" +
                        "nt.PhoneNumber\032Z\n\013PhoneNumber\022\016\n\006number\030" +
                        "\001 \001(\t\022;\n\004type\030\002 \001(\0162\'.com.yejunyu.protob" +
                        "uf.Student.PhoneType:\004HOME\"+\n\tPhoneType\022" +
                        "\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002B\"\n\024com.y" +
                        "ejunyu.protobufB\010DataInfoH\001"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_yejunyu_protobuf_Student_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_yejunyu_protobuf_Student_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_yejunyu_protobuf_Student_descriptor,
                new java.lang.String[]{"Name", "Age", "Address", "Phone",});
        internal_static_com_yejunyu_protobuf_Student_PhoneNumber_descriptor =
                internal_static_com_yejunyu_protobuf_Student_descriptor.getNestedTypes().get(0);
        internal_static_com_yejunyu_protobuf_Student_PhoneNumber_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_yejunyu_protobuf_Student_PhoneNumber_descriptor,
                new java.lang.String[]{"Number", "Type",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
